title: "{{cookiecutter.repo_name}}"
email: # TODO
description: "{{cookiecutter.your_name}}'s OctoPrint Plugin Statistics"
baseurl: "/"
url: "https://{{cookiecutter.github_username}}.github.io/{{cookiecutter.repo_name}}"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .flake8
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - pyproject.toml
